name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        java-version: '23'  # Especifica la versión de Java que usas
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x24 &

    - name: Build with Maven
      run: mvn clean install -B

    - name: Run tests
      run: mvn test
      env:
        DISPLAY: :99  # Especifica que las pruebas JavaFX deben usar el servidor Xvfb
